(*Chris Sohns*)

1.)
  (a)  2.6E3
  (b)  9.8456E3
  (c)  7.5835E2
  (d)  -3.0E-4
  (e)  2.85E-5

2.)
  (a)  35000000.0
  (b)  0.0000125
  (c)  1.5
  (d)  1000.0
  (e)  0.0001

3.)
  (a)  Spaces not allowed
  (b)  Hyphen not allowed
  (c)  Begins with a digit
  (d)  % not allowed
  (e)  BEGIN is a reserved word

4.)
Program Address;

Begin
  WriteLn('Chris Sohns')
  WriteLn('2815 Tartan Lane');
  WriteLn('Colorado Springs, CO  80920-5389');
  ReadLn;
End.

5.)
Program White_House;

Begin
  WriteLn('                                    01/10/95');
  WriteLn;
  WriteLn('Bill & Hill');
  WriteLn('1600 Pensilvania Avenue');
  WriteLn('Washington D.C.  66666-6666');
  WriteLn;
  WriteLn;
  WriteLn('Chris Sohns');
  WriteLn('2815 Tartan Lane');
  WriteLn('Colorado Springs, CO  80920-5389');
  WriteLn;
  WriteLn;
  WriteLn('Dear Mr. President:');
  ReadLn;
End.

6.)
Program Invintory;

Begin
  WriteLn('Item No.     Price');
  WriteLn;
  WriteLn('    2974      4.29');
  WriteLn('    6098     15.95');
  WriteLn('    8347      1.19');
  WriteLn('    9841     25.40');
  ReadLn;
End.

7.)
Program Daimond;

Begin
  WriteLn('*':4);
  WriteLn('***':5);
  WriteLn('*****':6);
  WriteLn('******':6);
  WriteLn('*****':6);
  WriteLn('***':5);
  WriteLn('*':4);
  ReadLn;
End.

8.)
Program Integers;

Begin
     WriteLn('Integer:  8');
     WriteLn('Real:  8.0');
     WriteLn('String:  Hi');
     ReadLn;
End.

9.)
  (a)  integer
  (b)  real
  (c)  real
  (d)  integer
  (e)  integer
  (f)  real

10.)
Program Math;

Begin
     WriteLn('125 + 379 = ',125+379);
     WriteLn('325 - 150 = ',325-150);
     WriteLn('65 x 45 = ',65*45);
     WriteLn('27 ö 8 = ',27/8:0:8);
     WriteLn('27 ö 8 = ',27 div 8,' with ',27 mod 8,' remaining');
     ReadLn;
End.